#!/usr/bin/env node

var express = require('express');
var debug = require('debug')('sara_uw_website');
var app = express();
var bodyParser = require('body-parser');

app.get('/', function (req, res) {
  res.redirect('/afterhours.html');
});

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
  extended: true
}));
app.use(express.static(__dirname + '/public'));

app.set('port', process.env.PORT || 8080);
var server = app.listen(app.get('port'), function() {
  debug('Express server listening on port ' + server.address().port);
});
